name: Install WSL
on:
  workflow_dispatch: {}
  push: {}
permissions: {}
jobs:
  install:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    strategy:
      matrix:
        include:
        - mode: appx
        - mode: install
        - mode: install-no-launch
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - name: "Windows: Update any pre-installed WSL"
      run: |
        # Sometimes this results in a HTTP 403 for some reason; in that case, we
        # need to retry.
        do {
          wsl --update
        } while ( -not $? )
        wsl --set-default-version 2

    - if: matrix.mode == 'appx'
      run: |
        # Install Debian by downloading the .AppxBundle manually
        ./collect-networking-logs.ps1 {
          Invoke-WebRequest https://github.com/microsoft/WSL/raw/master/distributions/DistributionInfo.json |
            Select-Object -ExpandProperty Content |
            ConvertFrom-JSON |
            Select-Object -ExpandProperty Distributions |
            Where-Object Name -EQ "Debian" |
            Select-Object -ExpandProperty Amd64PackageUrl |
            % { Invoke-WebRequest $_ -OutFile Debian.AppxBundle }
          Add-AppxPackage Debian.AppxBundle
          debian.exe install --root
          wsl -d debian /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install lsb-release
        }

    - if: matrix.mode == 'install'
      run: |
        ./collect-networking-logs.ps1 { wsl --install Debian }

    - if: matrix.mode == 'install-no-launch'
      run: |
        ./collect-networking-logs.ps1 { wsl --install --no-launch Debian }
    
    - run: >-
        wsl.exe -d Debian --exec /usr/bin/env DEBIAN_FRONTEND=noninteractive
        sh -c 'apt-get update && apt-get install --yes coreutils curl'

    - if: failure()
      uses: actions/upload-artifact@v4
      with:
        path: '*.zip'
        name: ${{ matrix.mode }}.zip
